force-app/main/default/objects/Lista_Super__c/Lista_Super__c.object-meta.xml
<CustomObject>
    <label>Lista Super</label>
    <nameField>
        <label>Lista Super Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas Super</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lista_Super_Producto__c/Lista_Super_Producto__c.object-meta.xml
<CustomObject>
    <label>Lista Super &amp; Producto</label>
    <nameField>
        <displayFormat>LSP-{000000}</displayFormat>
        <label>Lista Super Producto Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listas Super Producto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lista_Super_Producto__c/fields/Comprado__c.field-meta.xml
<CustomField>
    <fullName>Comprado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comprado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lista_Super_Producto__c/fields/Lista_Super__c.field-meta.xml
<CustomField>
    <fullName>Lista_Super__c</fullName>
    <label>Lista Super</label>
    <referenceTo>Lista_Super__c</referenceTo>
    <relationshipName>Listas_Super_Producto</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lista_Super_Producto__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lista_Super_Producto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipName>Listas_Super_Producto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <description>El objeto o categoría que pertenece un articulo</description>
    <label>Producto</label>
    <nameField>
        <label>Producto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación</fullName>
            </value>
            <value>
                <fullName>Carne</fullName>
            </value>
            <value>
                <fullName>Comida</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Fruta</fullName>
            </value>
            <value>
                <fullName>Gastos para la casa</fullName>
            </value>
            <value>
                <fullName>Higiene personal</fullName>
            </value>
            <value>
                <fullName>Lácteo</fullName>
            </value>
            <value>
                <fullName>Limpieza hogar</fullName>
            </value>
            <value>
                <fullName>Panificados</fullName>
            </value>
            <value>
                <fullName>Pileta</fullName>
            </value>
            <value>
                <fullName>Verdura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Producto__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <defaultValue>&quot;https://amazing-astro-115394-dev-ed--c.documentforce.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0685w00000ESYeQ&amp;operationContext=CHATTER&amp;contentId=05T5w00000p8GO4&quot;</defaultValue>
    <label>Image URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ListaSuperProductoController.cls
public with sharing class ListaSuperProductoController {

    @AuraEnabled(cacheable=true)
    public static List<Lista_Super_Producto__c> getProductsInListaSuper(String ListaSuperId) {

        return [
            SELECT Id, Name, Lista_Super__c, Producto__c, Producto__r.Name, Producto__r.Image_URL__c, Producto__r.Categoria__c, Nota__c, Comprado__c
            FROM Lista_Super_Producto__c
            WHERE Lista_Super__r.Id = :ListaSuperId
            ORDER BY Producto__r.Categoria__c, Producto__r.Name
        ];

    }

    @AuraEnabled
    public static Lista_Super_Producto__c insertProductoInListaSuper(String listaSuperId, String productoId) {

        Lista_Super_Producto__c newInsertInLista = new Lista_Super_Producto__c(
            Lista_Super__c = listaSuperId,
            Producto__c = productoId
        );

        INSERT newInsertInLista;

        return newInsertInLista;

    }

    @AuraEnabled
    public static String deleteProductoInListaSuper(String listaSuperId, String productoId) {

        Lista_Super_Producto__c productoInListaSuperToDelete = [SELECT Id FROM Lista_Super_Producto__c
                                                                WHERE Lista_Super__c = :listaSuperId AND Producto__c = :productoId
                                                                ];

        DELETE productoInListaSuperToDelete;

        return 'Success';

    }

    @AuraEnabled
    public static Lista_Super_Producto__c updateCompradoProductoInListaSuper(String listaSuperId, String productoId) {

        Lista_Super_Producto__c productoInListaSuperToUpdate = [SELECT Id, Comprado__c  FROM Lista_Super_Producto__c
                                                                WHERE Lista_Super__c = :listaSuperId AND Producto__c = :productoId
                                                                ];

        productoInListaSuperToUpdate.Comprado__c = !productoInListaSuperToUpdate.Comprado__c;                  

        UPDATE productoInListaSuperToUpdate;

        return productoInListaSuperToUpdate;

    }

}